name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare repo
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Test
        uses: onichandame/node-test-action@master

      - name: Lint
        run: yarn lint
        env:
          CI: true


      - name: Build
        run: yarn build
        env:
          CI: true
